
name: stemly_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.2.1
  provider: ^6.1.2
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  curved_navigation_bar: ^1.0.6

  # ----------------
  # Machine Learning
  # ----------------
  google_mlkit_text_recognition: ^0.13.0

  # ----------------
  # Firebase
  # ----------------
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.10
  firebase_analytics: ^11.6.0
  firebase_messaging: ^15.2.10
  firebase_crashlytics: ^4.3.10
  firebase_remote_config: ^5.5.0

  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^9.2.2
  http_parser: ^4.0.2
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1
  fl_chart: ^1.1.1
  function_tree: ^0.9.1
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/team/